### ISSUE TITLE
how to allow requests to nginx from ckan container

### ISSUE THREAD

**Issue by bonnland** [ckan/ckan-docker#220]
Hello,

I am very new to docker, and I am hoping someone can tell me if it is possible to configure this docker installation to allow HTTP requests from the ckan container to the nginx container. 

I am migrating a source-based installation of CKAN with spatial harvesting to this docker-based installation method.   I have run into a problem, however, because our source installation depends on harvesting dataset records from a web-accessible folder served by NGINX at http://localhost:9000.

This worked on our source install, where NGINX was a local service.  We changed Linux security settings to allow local HTTP requests, and we configured NGINX to serve local files on port 9000.   But from within the ckan-dev container, it seems that local requests are currently not allowed: 

```
ckan@7cf68ebdee83:~$ wget http://localhost:5000
--2025-05-14 01:23:00--  http://localhost:5000/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:5000... failed: Connection refused.
```

Is there a simple way to configure network settings, or maybe OS security settings, to allow this?   Please let me know if I can provide more information, in case my question does not contain enough information.   

Thank you in advance!

**Comment by kowh-ai** [comment]
I think it will be doable but could be painful. To access the NGINX server from within the CKAN container you would do something along the lines of: `ckan@28fdd3d58c00:~$ wget nginx:443` but out-of-the-box NGINX is listening on an SSL port (443) within the docker network  which will make it more difficult...

**Comment by bonnland** [comment]
Hi Brett,  

Thanks for your interest, and also your helpful youtube videos on setting up CKAN inside docker.  

I've dug a little further into docker tutorials, and it seems I can define a network "bridge" (hopefully the right term) to allow containers to communicate.   I asked CoPilot how I could modify docker-compose.dev.yml to allow requests from ckan-dev to nginx, and this is what it recommended adding:

```
version: '3.8'

services:
  ckan-dev:
    image: ckan-dev-image
    networks:
      - ckan-network
    environment:
      - NGINX_HOST=http://nginx
      - NGINX_PORT=80
    depends_on:
      - nginx

  nginx:
    image: nginx-image
    networks:
      - ckan-network
    ports:
      - "8080:80" # Optional: Expose NGINX to the host system

networks:
  ckan-network:
    driver: bridge
```
I have no idea how close this is to a workable solution, or a good idea..   Offhand, do you see any mistakes in this added configuration?   

Also, I'm a little curious why the docker-compose files for dev and production have different network configurations.   Any insights there?   Thanks again.
