### ISSUE TITLE
Timezone apply

### ISSUE THREAD

**Issue by Ryu-Joon-Hyuck** [ckan/ckan-docker#54]
Hi, Thank you for your Great Working!

I want to apply timezone in docker container.
But it doesn't work for all.

Help me, please.

CONFIG:
1. .env
```bash
,,,
#TZ=UTC
TZ=Asia/Seoul
...
```
2. docker-compose.yml
```
version: "3"

volumes:
  ckan_storage:
  pg_data:
  solr_data:

services:

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build:
      context: nginx/
      dockerfile: Dockerfile
    depends_on:
      ckan:
        condition: service_healthy
    ports:
      - "0.0.0.0:${NGINX_PORT_HOST}:${NGINX_PORT}"
      - "0.0.0.0:${NGINX_SSLPORT_HOST}:${NGINX_SSLPORT}"
    environment:
      - TZ=${TZ}

  ckan:
    container_name: ${CKAN_CONTAINER_NAME}
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "0.0.0.0:${CKAN_PORT_HOST}:${CKAN_PORT}"
    volumes:
      - ckan_storage:/var/lib/ckan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5000"]

  datapusher:
    container_name: ${DATAPUSHER_CONTAINER_NAME}
    image: ckan/ckan-base-datapusher:${DATAPUSHER_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8800"]
    environment:
      - TZ=${TZ}

  db:
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    build:
      context: postgresql/
      args:
       - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
      - TZ=${TZ}
    ports:
      - "0.0.0.0:${POSTGRES_PORT_HOST}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: ${SOLR_CONTAINER_NAME}
    image: ckan/ckan-solr:${SOLR_IMAGE_VERSION}
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]
    environment:
      - TZ=${TZ}

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
    environment:
      - TZ=${TZ}
```

Result:
1. continer, docker log both ok.
	- nginx
	- ckan
4. contianer ok, but docker log is not working.
	- ckan
	- db
	- solr
	- redis
5. contianer, docker log both not not working
	- datapusher
